[[headers]]
  for = "/*"
    [headers.values]
      Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com/; frame-ancestors 'self'"
